name: "Quality"
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - master

env:
  CI: true
  CACHE_PATH: '**/node_modules'

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: "${{ runner.os }}-modules-"
    - run: yarn install

  lint_source:
    name: Lint Source
    runs-on: ubuntu-latest
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2.1.7
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: ESLint
        run: yarn lint:js


  types:
    name: "Type Correctness"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [install_dependencies]

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: ${{ env.CACHE_PATH }}
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install
    # running with yarn causes tsc to hang
    - run: tsc --build --clean && tsc --build
